# https://dev.to/rolanddoda/deploy-to-github-pages-like-a-pro-with-github-actions-4hdg

name: gh-pages

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Clean install dependencies
        run: yarn install --immutable
      - name: Deploy
        run: |
          git checkout --orphan gh-pages
          yarn build
          git config user.name "sgosiaco"
          git config user.email "sgosiaco@me.com"
          git --work-tree dist add --all
          git --work-tree dist commit -m 'Deploy'
          git push origin HEAD:gh-pages --force
          rm -r dist
          git checkout -f master
          git branch -D gh-pages
